// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVzf-W9wAoMG8haMNA2EG4lXk-edKq7yE',
    appId: '1:758407873138:web:296b2c966e4bbe4b0338eb',
    messagingSenderId: '758407873138',
    projectId: 'lessons-chat',
    authDomain: 'lessons-chat.firebaseapp.com',
    storageBucket: 'lessons-chat.appspot.com',
    measurementId: 'G-EMV7TP6TR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIYehLkd1LI3LEeWr1L6pR8QSr6uQGBzA',
    appId: '1:758407873138:android:7c02ff305561b52c0338eb',
    messagingSenderId: '758407873138',
    projectId: 'lessons-chat',
    storageBucket: 'lessons-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEyjhrycLaU-VQGQX1ae3Fms6GvxoC1u4',
    appId: '1:758407873138:ios:7f1bc98558498fd10338eb',
    messagingSenderId: '758407873138',
    projectId: 'lessons-chat',
    storageBucket: 'lessons-chat.appspot.com',
    iosClientId: '758407873138-cdbml1obgerk4diesud92d3o9fsrhee6.apps.googleusercontent.com',
    iosBundleId: 'com.example.lessonsChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEyjhrycLaU-VQGQX1ae3Fms6GvxoC1u4',
    appId: '1:758407873138:ios:7f1bc98558498fd10338eb',
    messagingSenderId: '758407873138',
    projectId: 'lessons-chat',
    storageBucket: 'lessons-chat.appspot.com',
    iosClientId: '758407873138-cdbml1obgerk4diesud92d3o9fsrhee6.apps.googleusercontent.com',
    iosBundleId: 'com.example.lessonsChat',
  );
}
